		index index.php;

		location ^~ /private/ {
				return 404;
		}

		location = /location-release.apk {
				add_header Cache-Control "no-store";
				try_files /location-release.apk =404;
		}

		location = /admin {
				return 301 /admin/;
		}

		location /admin/ {
				try_files $uri $uri/ =404;
		}


		location = /_AMapService/maps {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				proxy_ssl_server_name on;
				proxy_set_header Host webapi.amap.com;
				proxy_pass https://webapi.amap.com/maps;
		}

		location = /_AMapService/appmaptile {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				proxy_ssl_server_name on;
				proxy_set_header Host webrd01.is.autonavi.com;
				proxy_pass https://webrd01.is.autonavi.com/appmaptile;
		}

		location = /_AMapService/v4/map/styles {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				set $args "$args&jscode=7734700d1d524ff04de41212034cb12f";
				proxy_ssl_server_name on;
				proxy_set_header Host webapi.amap.com;
				proxy_pass https://webapi.amap.com/v4/map/styles;
		}

		location = /_AMapService/v3/vectormap {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				set $args "$args&jscode=7734700d1d524ff04de41212034cb12f";
				proxy_ssl_server_name on;
				proxy_set_header Host fmap01.amap.com;
				proxy_pass https://fmap01.amap.com/v3/vectormap;
		}

		location ^~ /_AMapService/ {
				if ($http_user_agent !~* "loc-app") {
						return 403;
				}
				set $args "$args&jscode=7734700d1d524ff04de41212034cb12f";
				proxy_ssl_server_name on;
				proxy_set_header Host restapi.amap.com;
				proxy_pass https://restapi.amap.com/;
		}

		location /api/ {
				try_files $uri =404;
		}

		location / {
				return 404;
		}

