plugins {
    id "com.android.library"
}

android {
    namespace = "com.familylocation.common"
    compileSdk = 35
    buildToolsVersion = "36.0.0"

    defaultConfig {
        minSdk = 29
    }

    sourceSets {
        main {
            manifest.srcFile("AndroidManifest.xml")
            java.srcDirs("src")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}
